### ISSUE TITLE
大佬大佬，请问Minihttpserver.jar文件发布在哪

### ISSUE THREAD

**Issue by DragonYH** [BalloonUpdate/McVersioning#1]
如题

**Comment by asforest** [comment]
MiniHttpServer是LittleServer的代码删减版，因为功能太过简单就没有单独发布仓库。
MiniHttpServer就是个纯静态httpserver。nginx，hfs，宝塔都可以替换掉它，
此外这个文件代码太简单，不会有bug，所以大概率不会再发布更新

构建文件：[MiniHttpServer-0.0.0.jar.zip](https://github.com/BalloonUpdate/McVersioning/files/9925157/MiniHttpServer-0.0.0.jar.zip)

源代码：[MiniHttpServer.zip](https://github.com/BalloonUpdate/McVersioning/files/9925158/MiniHttpServer.zip)
